FROM ubuntu:16.04

MAINTAINER MModal

WORKDIR /opt

# Download latest version of the code and install dependencies
RUN apt-get update
RUN apt-get install -y wget
RUN apt-get install -y curl
RUN apt-get install -y git-all
RUN apt-get install -y mercurial
RUN apt-get install -y sudo
RUN apt-get install -y rsyslog
#RUN apt-get install -y gcc
#RUN apt-get install -y g++
#RUN apt-get install -y make
#RUN apt-get install -y cmake
#RUN apt-get install -y yasm

